-- ============================================================================
-- ESQUEMA DE BASE DE DATOS PARA SUPABASE (POSTGRESQL)
-- SISTEMA DE CONTROL DE ACCESO RESIDENCIAL
-- ============================================================================

-- 1. LIMPIEZA PREVIA DE TABLAS Y POLÍTICAS
DROP TABLE IF EXISTS accesos CASCADE;
DROP TABLE IF EXISTS residentes CASCADE;
DROP TABLE IF EXISTS visitantes CASCADE;

-- ============================================================================
-- 2. TABLAS RELACIONALES (POSTGRESQL)
-- ============================================================================

-- TABLA: residentes
CREATE TABLE residentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    numero_casa TEXT NOT NULL UNIQUE,
    telefono TEXT,
    correo TEXT,
    fecha_registro TIMESTAMPTZ DEFAULT NOW()
);

-- TABLA: visitantes
CREATE TABLE visitantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    identificacion TEXT NOT NULL,
    telefono TEXT,
    tipo_visitante TEXT DEFAULT 'Visita General',
    fecha_registro TIMESTAMPTZ DEFAULT NOW()
);

-- TABLA: accesos
CREATE TABLE accesos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    residente_id BIGINT NOT NULL REFERENCES residentes(id) ON DELETE CASCADE,
    visitante_id BIGINT NOT NULL REFERENCES visitantes(id) ON DELETE CASCADE,
    motivo TEXT NOT NULL,
    fecha_entrada TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_salida TIMESTAMPTZ,
    estado TEXT DEFAULT 'EN FRACCIONAMIENTO',
    observaciones TEXT
);

-- ============================================================================
-- 3. HABILITAR POLITICAS RLS (Row Level Security) PARA ACCESO PÚBLICO
-- ============================================================================

ALTER TABLE residentes ENABLE ROW LEVEL SECURITY;
ALTER TABLE visitantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE accesos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir todo en residentes" ON residentes;
DROP POLICY IF EXISTS "Permitir todo en visitantes" ON visitantes;
DROP POLICY IF EXISTS "Permitir todo en accesos" ON accesos;

CREATE POLICY "Permitir todo en residentes" ON residentes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo en visitantes" ON visitantes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo en accesos" ON accesos FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- 4. DATOS INICIALES DE PRUEBA
-- ============================================================================

INSERT INTO residentes (nombre, numero_casa, telefono, correo) VALUES
('Carlos Mendoza García', 'Casa 101', '555-123-4567', 'carlos.mendoza@email.com'),
('María Elena López', 'Casa 102', '555-987-6543', 'maria.lopez@email.com'),
('Roberto Fernández', 'Depto 201-A', '555-456-7890', 'roberto.f@email.com'),
('Laura Sofía Ramírez', 'Casa 205', '555-321-6548', 'laura.ramirez@email.com'),
('Jorge Alberto Torres', 'Depto 304-B', '555-789-1234', 'jorge.torres@email.com');

INSERT INTO visitantes (nombre, identificacion, telefono, tipo_visitante) VALUES
('Ana Patricia Gómez', 'INE-84729104', '555-111-2233', 'Familiar'),
('Fernando Silva Ruiz', 'LIC-92837129', '555-444-5566', 'Proveedor'),
('Técnico Paquetetrack (Luis Pérez)', 'GAB-10293847', '555-777-8899', 'Servicio/Mantenimiento'),
('Claudia Ramos Morales', 'INE-55443322', '555-999-0011', 'Visita General'),
('Ricardo Morales Vega', 'INE-11223344', '555-666-7788', 'Familiar');

INSERT INTO accesos (residente_id, visitante_id, motivo, fecha_entrada, fecha_salida, estado, observaciones) VALUES
(1, 1, 'Reunión familiar de fin de semana', NOW() - INTERVAL '5 hours', NOW() - INTERVAL '1 hour', 'SALIDO', 'Nissan Sentra Gris Placas ABC-123'),
(2, 2, 'Entrega de material de construcción', NOW() - INTERVAL '3 hours', NOW() - INTERVAL '2 hours', 'SALIDO', 'Camión de carga 3 toneladas'),
(1, 3, 'Entrega de paquete de mensajería', NOW() - INTERVAL '1 hour', NULL, 'EN FRACCIONAMIENTO', 'Camioneta identificada de mensajería'),
(3, 4, 'Visita personal a departamento', NOW() - INTERVAL '30 minutes', NULL, 'EN FRACCIONAMIENTO', 'Peatonal, mostró INE en caseta'),
(4, 5, 'Comida de cumpleaños', NOW() - INTERVAL '15 minutes', NULL, 'EN FRACCIONAMIENTO', 'Vehículo Ford Mustang Azul');
